vich_uploader:
    db_driver: orm

    mappings:
        art_image:
            uri_prefix: /uploads/art
            upload_destination: '%kernel.project_dir%/public/uploads/art'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
