CREATE TABLE art (id INT AUTO_INCREMENT NOT NULL, artiste_id INT NOT NULL, name VARCHAR(255) NOT NULL, img VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, categories VARCHAR(255) NOT NULL, INDEX IDX_FC35D65421D25844 (artiste_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL,
                    email VARCHAR(180) NOT NULL, 
                    roles JSON NOT NULL COMMENT '(DC2Type:json)',
                    password VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL,
                    UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email),
                    PRIMARY KEY(id))
                    DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE demandes (id INT AUTO_INCREMENT NOT NULL, demandeurs_id INT DEFAULT NULL, artiste_id INT DEFAULT NULL, message LONGTEXT NOT NULL, reponse LONGTEXT DEFAULT NULL, INDEX IDX_BD940CBBF553F29B (demandeurs_id), INDEX IDX_BD940CBB21D25844 (artiste_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, img VARCHAR(255) NOT NULL, date DATETIME NOT NULL, lieu VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE service_request (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_F413DD03A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', available_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', delivered_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE art ADD CONSTRAINT FK_FC35D65421D25844 FOREIGN KEY (artiste_id) REFERENCES user (id);
ALTER TABLE demandes ADD CONSTRAINT FK_BD940CBBF553F29B FOREIGN KEY (demandeurs_id) REFERENCES user (id);
ALTER TABLE demandes ADD CONSTRAINT FK_BD940CBB21D25844 FOREIGN KEY (artiste_id) REFERENCES user (id);
ALTER TABLE service_request ADD CONSTRAINT FK_F413DD03A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
